### ISSUE TITLE
library.json is invalid

### ISSUE THREAD

**Issue by plueschpruem** [Bodmer/JSON_Decoder#1]
Also do you have any idea why the original library compiles in Arduino, but not in PlatformIO?
I always get an error regarding a vtable with the example.

Was hoping your fork would work :-)

**Comment by Bodmer** [comment]
Looks like it is a format issue to do with square/curly brackets. I think the library.json file is now OK.

Unfortunately I know very little about the PlatformIO environment and what may need to be done to fix the issue.

The code area that seems to be the troublesome bit was inherited from Daniel Eichhorn's original so I have not tinkered with that.

**Comment by plueschpruem** [comment]
Nice. Library installs now.
Thanks again for the fast fixes!

**Comment by Bodmer** [comment]
Thanks for reporting this and glad to hear all is well now!

**Comment by plueschpruem** [comment]
Still doesn't compile, but tomorrow is another day.
I got the parser to compile with one of the weather station examples, but those are huge and even more complicated than the parser itself, so I cannot spot the fix.
I am pretty sure it's some simple fix. Will ask in the PIO forum.

**Comment by Bodmer** [comment]
OK, thanks for your support. If you find a solution then do please post back here and I will update the library.

**Comment by plueschpruem** [comment]
OK, turns out that you need to put ExampleParser.cpp and ExampleParser.h into /src, not into /include.
So that solves that mystery…

**Comment by emogg** [comment]
Platformio complains about not being able to parse manifest.  The online json validator https://jsonlint.com/ says this about library.json

---------------------------
Error: Parse error on line 13:
...ntainer": true	},	{		"name": "altrunn
---------------------^
Expecting 'STRING', got '{'
----------------------------------

Can you fix it please?

**Comment by Bodmer** [comment]
Fixed.

**Comment by emogg** [comment]
Excellent, thank you for the quick fix
