### ISSUE TITLE
Please fork properly

### ISSUE THREAD

**Issue by gnbl** [Bodmer/JSON_Decoder#2]
Hi Bodmer,

could you try and make this a proper fork of https://github.com/altrunner/json-streaming-parser so one can take full advantage of the git/GitHub features?
The downside is that with currently 53 forks of https://github.com/squix78/json-streaming-parser even these features are only little help to understand which one is "the best".
Did you only rename the library or did you make other changes as well?

Thanks!

**Comment by Bodmer** [comment]
This library copy was originally created for debugging an Arduino sketch and this required the library files to be renamed so this copy could co-exist with the original library and allow a performance comparison. 

A summary of the changes is in the ReadMe.

I have had a look at approaches to re-linking to changes when compared with the original libraries but this has not been very fruitful so is unlikely to happen.
